language: java
jdk:
  - oraclejdk8

services:
  - docker

env:
  - JDBC_DATABASE_URL=jdbc:postgresql://172.17.0.2:5432/postgres?user=postgres

cache:
  directories:
    - node_modules
    - $HOME/.m2

before_install:
  - docker pull postgres
  - docker run -d -p 127.0.0.2:5432:5432 --name bradgardenDB -d postgres:latest
  - npm install -g dredd@3.4.2
script:
- mvn package
- cat sql/bradgardenDB.sql sql/insert_members.sql | psql -h 127.0.0.2 -p 5432 -U postgres
- dredd