language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull postgres
  - docker run -d -p 127.0.0.2:5432:5432 --name bradgardenDB -d postgres:latest
  - npm install -g dredd@3.4.2
script:
- mvn test -B
- ./scipts/dreddTest.sh