version: '3.1'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        container_name: bddb
        command: ADD dockerfiles/db/bradgardenDB.sql /docker-entrypoint-initdb.d/  

    web:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - db
        container_name: bdweb
