version: '2'
services:
    db:
        image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bradgarden
        container_name: bddb
        command: ADD dockerfiles/db/bradgardenDB.sql /docker-entrypoint-initdb.d/  

    web:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - db
        container_name: bdweb
